services:
  web:
    build: .
    command: python djangorest/manage.py runserver 0.0.0.0:8000
    ports:
      - 127.0.0.1:8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=dummy_key
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    volumes: 
      - ./djangorest/:/opt/app/djangorest