# Generated by Django 4.0.4 on 2022-05-09 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.sensortype', unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='uuid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
