# Generated by Django 4.0.4 on 2022-05-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_alter_sensor_kind_alter_sensortype_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
